apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-app
  namespace: dev
spec:
  selector:
    matchLabels:
      app: sinatra
  replicas: 2
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      containers:
      - name: sinatra
        image: "erikap/ruby-sinatra:1.1.0"

---

apiVersion: v1
kind: Service
metadata:
  name: sinatra-service
  namespace: dev
  labels:
    app: sinatra
spec:
  type: ClusterIP
  selector:
    app: sinatra
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP