apiVersion: v1
kind: Secret
metadata:
  name: backend-cred-01
  namespace: dev
type: Opaque
stringData:
  USERNAME: admin123
  PASSWORD: t0p-Secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sinatra-app-files
  namespace: dev
data:
  sinatra_app.rb: |
    require "sinatra/base"
    require "socket"

    class SinatraApp < Sinatra::Base
      get "/" do
        # Print X-Forwarded-* headers
        # puts "X-Forwarded-Host: #{request.env["HTTP_X_FORWARDED_HOST"].inspect}"
        # puts "X-Forwarded-For: #{request.env["HTTP_X_FORWARDED_FOR"].inspect}"
        # puts "X-Forwarded-Proto: #{request.env["HTTP_X_FORWARDED_PROTO"].inspect}"
        # puts "X-Forwarded-Port: #{request.env["HTTP_X_FORWARDED_PORT"].inspect}"
        # puts "X-Real-IP: #{request.env["HTTP_X_REAL_IP"].inspect}"
        # puts "Server Hostname: #{Socket.gethostname}"
        # puts "Request Host: #{request.host}"

        query_params = request.query_string
        formatted_params = query_params.empty? ? "" : "?" + query_params
        client_ip = request.ip
        request_host = request.host
        server_hostname = Socket.gethostname
        puts "#{Time.now} - #{client_ip} - #{request_host} - #{server_hostname} -GET /#{formatted_params}"
        # puts "some message with a newline\nand more text"

        erb :index
      end
    end

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sinatra-app-views-files
  namespace: dev
data:
  index.erb: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Sinatra Demo</title>
      <link rel="stylesheet" href="/styles.css">
    </head>
    <body>
      <h1>Hello, Sinatra! Test 1</h1>
      <img src="/jelly-beans.jpg" />
      <pre>
        Client IP: <%= request.ip %>
        ENV['BACKEND_01_USERNAME']: <%= ENV['BACKEND_01_USERNAME'] %>
        ENV['BACKEND_01_PASSWORD']: <%= ENV['BACKEND_01_PASSWORD'] %>
      </pre>
    </body>
    </html>
