apiVersion: v1
kind: Secret
metadata:
  name: backend-cred-01
  namespace: dev
type: Opaque
stringData:
  USERNAME: admin123
  PASSWORD: t0p-Secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sinatra-app-files
  namespace: dev
data:
  sinatra_app.rb: |
    require "sinatra/base"
    require "socket"

    class SinatraApp < Sinatra::Base
      get "/" do
        query_params = request.query_string
        formatted_params = query_params.empty? ? "" : "?" + query_params
        client_ip = request.ip
        request_host = request.host
        server_hostname = Socket.gethostname
        puts "#{Time.now} - #{client_ip} - #{request_host} - #{server_hostname} -GET /#{formatted_params}"

        erb :index
      end
    end

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sinatra-app-views-files
  namespace: dev
data:
  index.erb: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Cloud Developer Assessment 02</title>
      <link rel="stylesheet" href="/styles.css">
    </head>
    <body>
      <pre>
        ENV['BACKEND_01_USERNAME']: <%= ENV['BACKEND_01_USERNAME'] %>
        ENV['BACKEND_01_PASSWORD']: <%= ENV['BACKEND_01_PASSWORD'] %>

        request.ip: <%= request.ip %>
        request.host: <%= request.host %>
        Socket.gethostname: <%= Socket.gethostname %>
      </pre>
    </body>
    </html>
