apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: maybank-cloud-assessment-02
  region: ap-southeast-5

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
