apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
